name: Security Scan

on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Run Scan
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          VT_API_KEY: ${{ secrets.VT_API_KEY }}
          CI: "true"
        run: python main.py . --todo